---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "8"


sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm


before_install:
  # start your web application and listen on `localhost`
  #- google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
  - npm config set spin false
  - npm --version

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - npm test
